### PR TITLE
feat: participant change rates (monthly)

### PR DESCRIPTION
**Pull request by bajtos**
Implement a new API endpoint `GET /participants/change-rates`

Links:
- https://github.com/filecoin-station/roadmap/issues/91

### CODE REVIEW

**Comment by bajtos** [comment]
Discussion point:

In the past, I created one endpoint for each chart. I am wondering if I should keep doing the same for churn-rate/growth-rate/retention-rate values because the SQL query and the code to calculate the rates will be very similar for all three rates. Maybe we can have a single endpoint for all three rates?

E.g. `GET /participants/change-rates`:

```json
[
  { "month": "2024-03-01", "churnRate": 0.2, "growthRate": 0.1, "retentionRate": 0.7 }
]
```

@juliangruber WDYT?

**Review by juliangruber — APPROVED** [review]
Great work!

**Comment by juliangruber** [comment]
> Discussion point:
> 
> In the past, I created one endpoint for each chart. I am wondering if I should keep doing the same for churn-rate/growth-rate/retention-rate values. The SQL query and the code to calculate the rates will be very similar for all three rates. Maybe we can have a single endpoint for all three rates?
> 
> E.g. `GET /participants/change-rates`:
> 
> ```json
> [
>   { "month": "2024-03-01", "churnRate": 0.2, "growthRate": 0.1, "retentionRate": 0.7 }
> ]
> ```
> 
> @juliangruber WDYT?

I don't have a strong opinion about this. I believe this API is still too young to make a well informed decision. Combining them seems less wasteful, and simpler, so I think it's a good idea for now 👍

**Comment by bajtos** [comment]
> > Discussion point:
> > In the past, I created one endpoint for each chart. I am wondering if I should keep doing the same for churn-rate/growth-rate/retention-rate values. The SQL query and the code to calculate the rates will be very similar for all three rates. Maybe we can have a single endpoint for all three rates?
> > E.g. `GET /participants/change-rates`:
> > ```json
> > [
> >   { "month": "2024-03-01", "churnRate": 0.2, "growthRate": 0.1, "retentionRate": 0.7 }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @juliangruber WDYT?
> 
> I don't have a strong opinion about this. I believe this API is still too young to make a well informed decision. Combining them seems less wasteful, and simpler, so I think it's a good idea for now 👍

Done 💪🏻 

The pull request is ready for final review and landing.

**Review by juliangruber — APPROVED** [review]
great work :)

**Pull request merged**
